# Generated by Django 4.2.1 on 2023-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='hallo', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
